# PHP CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-php/ for more details
version: 2

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: cimg/php:7.4
      #- image: circleci/mysql:5.7
    resource_class: medium
    parallelism: 2
    working_directory: ~/tasklist

    steps:
      - checkout
      - run: cd .. && git clone --depth 5 "$CLONING_URL" --branch "$BRANCH"
      - run: cd .. && sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File
      - run: cd .. && yes '' |sudo pecl install mailparse || true

      # Download and cache composer dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "~/xguard-schedule/composer.json" }}v
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Rollback to composer v1
      - run: composer --version

      # Composer install
      - run: cd ~/xguard-schedule && composer install -n --prefer-dist

      # Download cached composer dependencies
      - save_cache:
          key: v1-dependencies-{{ checksum "~/xguard-schedule/composer.json" }}
          paths:
            - ./vendor

      # Create and move tasklist plugin into the xguard-schedule/packages/tasklist/ directory
      - run: cd ~/xguard-schedule && sudo mkdir packages
      - run: cd ~/xguard-schedule/packages && sudo mkdir tasklist
      - run: sudo rm -r ~/xguard-schedule/vendor/xguard/tasklist/*
      - run: cd .. && sudo cp -r ~/tasklist/* ~/xguard-schedule/packages/tasklist/
      - run: cd .. && sudo cp -r ~/tasklist/* ~/xguard-schedule/vendor/xguard/tasklist/

      # Run php unit tests
      - run:
          name: "Run Tests in Parallel"
          command: |
            cd ~/xguard-schedule && phpdbg -d memory_limit=64G -qrr vendor/bin/paratest -p2 packages/tasklist/tests

      #Jest

      - run:
          name: "install dependencies"
          command: |
            cd ~/xguard-schedule/packages/tasklist && sudo npm install


      - run:
          name: "Run Frontend Jest Tests"
          command: |
            cd ~/xguard-schedule/packages/tasklist && sudo npm test




